services:
  - type: web
    name: ethos-web
    region: oregon
    rootDir: .
    env: node
    buildCommand: |
      npm ci
      npm run build --workspace=@ethos/web
    startCommand: npm run start --workspace=@ethos/web
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      # Inject API internal networking info
      - key: API_URL
        fromService:
          name: ethos-api
          type: web
          property: url

  - type: web
    name: ethos-api
    region: oregon
    rootDir: .
    env: node
    buildCommand: |
      npm ci
      npm run build --workspace=@ethos/api
    startCommand: npm run start --workspace=@ethos/api
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
