services:
  - type: web
    name: ethos-web
    region: oregon
    rootDir: .
    env: node
    buildCommand: |
      npm ci --omit=dev
      npm run build
    startCommand: npm run start --workspace=@ethos/web
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: API_HOST
        fromService:
          name: ethos-api
          type: web
          property: host
      - key: API_PORT
        fromService:
          name: ethos-api
          type: web
          property: port

  - type: web
    name: ethos-api
    region: oregon
    rootDir: .
    env: node
    buildCommand: |
      npm ci
      npm run build --workspace=@ethos/api
    startCommand: npm run start --workspace=@ethos/api
    envVars:
      - key: NODE_VERSION
        value: 20.18.0